apiVersion: v1
kind: Service
metadata:
  name: {{ template "cedrusdata.fullname" . }}
  labels:
    app: {{ template "cedrusdata.name" . }}
    chart: {{ template "cedrusdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range $key, $value := .Values.coordinator.additionalExposedPorts }}
    - port: {{ $value.servicePort }}
      name: {{ $value.name }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    app: {{ template "cedrusdata.name" . }}
    release: {{ .Release.Name }}
    component: coordinator
